### ISSUE TITLE
Drupal deployment

### ISSUE THREAD

**Issue by manuelfischer** [freifunk-bingen/docs-ffbin#2]
Drupal deployment ToDo:
- Cache
- CSS & JS Aggregation
- Cronjob für Drupal Cron
- Drupal-Folder ins Webroot verschieben

**Comment by sbschuermann** [comment]
- "Neuigkeiten" formatieren
- Media zugänglich machen zum Upload von im Text verlinkten Bildern und Dateien
- "Kontakt" - Allgemeines Kontakformular neben Impressum
- ?? Allgemeines Forum anonym lesbar machen und vom User-Menu ins Main-Menu verschieben ??

**Comment by manuelfischer** [comment]
- Hard-Links im View für neue Forenbeiträge anpassen

**Comment by sbschuermann** [comment]
- Im Media-Modul PDF-Upload erlauben (odt?, svg?)

**Comment by manuelfischer** [comment]
Media-Modul ist jetzt nochmal angepasst, andere CKEditor Version und ein Button zum Einfügen von Media-Dateien (unten rechts).

**Comment by manuelfischer** [comment]
Tadaa
