### ISSUE TITLE
Anleitung schreiben

### ISSUE THREAD

**Issue by manuelfischer** [freifunk-bingen/docs-ffbin#3]
Die Anleitung zum Flashen muss geschrieben werden. Idealerweise mit Bildern / Screenshots.
Ich kann gerne das Themeing übernehmen.

Sollen wir die Downloads und Anleitung unter einem Menüpunkt (z.B. "Einrichtung") zusammenfassen?
Also so:
. Einrichtung
| - Anleitung
| - Firmware-Download

**Comment by sbschuermann** [comment]
Findsch gut, kann dann auch noch eine Seite hin, auf der wir unser "Angebot" für Router-Installation durch uns beschreiben.

Idee: Wir bieten eine Mitgliedschaft im Verein als "Fördermitgliedschaft" an, z.B. 5€ im Monat. "Fördernde Mitglieder" (Also Firmen, Caf´es, etc) erhalten speziellen Support durch uns. Die Fördermitgliedschafts-Beiträge werden natürlich für die gemeinnützigen Zwecke des Vereins verwendet.

**Comment by manuelfischer** [comment]
Text, Karte, Theme und Fotos hab ich denk ich verständlich und übersichtlich fertig. Ich werte das (für mein Wohlbefinden) als closed.
