### ISSUE TITLE
Freifunk API

### ISSUE THREAD

**Issue by manuelfischer** [freifunk-bingen/docs-ffbin#5]
API-File habe ist schon erstellt: https://www.freifunk-bingen.de/ffapi.json
Sobald die Webseite public ist, stelle ich ein Pull-Request an Freifunk. Damit erscheinen wir als Community auf der Freifunk-Webseite.

**Comment by manuelfischer** [comment]
freifunk/directory.api.freifunk.net#236

**Comment by donnerkarlson** [comment]
hat das geklappt? "All checks have failed"

**Comment by manuelfischer** [comment]
sollte klappen, die Fehler liegen bei anderen Communities:
https://travis-ci.org/freifunk/directory.api.freifunk.net/builds/75577652
