### ISSUE TITLE
Benutzerregistrierung (Drupal)

### ISSUE THREAD

**Issue by manuelfischer** [freifunk-bingen/docs-ffbin#6]
Momentan können sich Benutzer registrieren. Nur gibt es dafür keinen wirklichen Mehrwert. Was könnten wir (außer dem Forum) anbieten? Oder schalten wir die Registrierung komplett ab (damit würde evtl. auch die Kommentierfunktion für Artikel wegfallen)

**Comment by sbschuermann** [comment]
Ich würde das Forum (den Allgemeinen Teil) noch verfügbar machen. Posten ist dann nur nach Anmeldung möglich, Kommentare ebenfalls. Vielleicht erreichen wir in Zukunbft auch noch andere Leute als "aktive" Mitglieder, die können dann auch Artikel schreiben...

**Comment by manuelfischer** [comment]
Also der öffentliche Forenbereich: Leseberechtigung für Gäste?
