### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by sbschuermann** [freifunk-bingen/docs-ffbin#7]
Das Logo auf der Webseite wüde ich noch um den Schriftzug "freifunk bingen" in der Alternate Gothic ergänzen..wäre eine durchgängige CI.

**Comment by manuelfischer** [comment]
Ist leider keine lizenzfreie Font, es sieht auch etwas merkwürdig aus wenn die Schrift neben dem Logo eine andere ist finde ich

**Comment by sbschuermann** [comment]
Ist halt die Schrift, die so auf allen Werbematerialien, inkl. Webseite von freifunk.net verwendet wird. Wegen Lizenz würde ich mir da erstmal keine Gedanken machen, gibt's ja auch überall zum Download. Ich würde halt das "Freifunk Bingen" gerne etwas prominenter haben. Mit den Schriften soll man es sicher nicht übertreiben, sonst siehts schnell aus wie Kindergarten. Vielleicht fällt ?Astrid? (ich mag sie nicht immer "Deine Schwester" nennen) ja was dazu ein...

**Comment by manuelfischer** [comment]
freifunk.net haben sich dafür eine Lizenz besorgt, siehe http://wiki.freifunk.net/Freifunk-Styles#Freifunk-Font
Also entweder von denen den Schriftzug machen lassen, oder eine freie Schrift nutzen.
